import 'package:uuid/uuid.dart';
import '../modules/catalog/domain/entities/product.dart';

const uuid = Uuid();

final mockProducts = <Product>[
  // Pastilha de Freio
  Product(
    id: uuid.v4(),
    name: 'Pastilha Freio Traseira Toyota Corolla 2015-2019',
    description:
        'Pastilha de freio semi-metálica de alta performance para Toyota Corolla',
    sku: 'PST-TOYOTA-COROLLA-TRAS',
    gtin: '7898765432101',
    partNumber: 'TAT-04465-BR',
    oemCode: '04465-02380',
    brand: 'Nakata',
    price: 89.90,
    qualityRanking: QualityRanking.genuine,
    ncm: '87087099',
    cest: '2401100',
    cst: '070',
    monophasic: false,
    origin: MerchandiseOrigin.national,
    cfop: '5102',
    currentStock: 24,
    minimumStock: 5,
    maximumStock: 50,
    leadTimeDays: 7,
    physicalLocation: 'Corredor A, Prateleira 3',
    weight: 0.450,
    length: 10.5,
    width: 8.2,
    height: 5.0,
    seoTitle: 'Pastilha Freio Traseira Toyota Corolla 2015 a 2019',
    keywords: ['pastilha freio', 'corolla', 'toyota', 'freio traseiro'],
    imageUrls: [
      'https://images.unsplash.com/photo-1486262715619-3417b3999ddd?w=600&h=400&fit=crop',
    ],
    compatibilities: [
      VehicleCompatibility(
        manufacturer: 'Toyota',
        model: 'Corolla',
        version: '1.8 16V XEi',
        yearStart: 2015,
        yearEnd: 2019,
        motorization: '1.8',
        fuelType: FuelType.flex,
        position: 'Traseiro',
      ),
    ],
  ),

  // Óleo de Motor
  Product(
    id: uuid.v4(),
    name: 'Óleo Motor 10W-40 Sintético 4L',
    description:
        'Óleo lubrificante sintético 10W-40 para motores a gasolina e diesel',
    sku: 'OLE-10W40-4L-SINT',
    gtin: '7898765432102',
    partNumber: 'OLE-10W40-SYN',
    oemCode: '',
    brand: 'Mobil',
    price: 45.50,
    qualityRanking: QualityRanking.original,
    ncm: '27101920',
    cest: '2705000',
    cst: '000',
    monophasic: true,
    origin: MerchandiseOrigin.directImport,
    cfop: '5102',
    currentStock: 38,
    minimumStock: 10,
    maximumStock: 100,
    leadTimeDays: 14,
    physicalLocation: 'Corredor B, Prateleira 2',
    weight: 4.1,
    length: 12.0,
    width: 10.0,
    height: 25.0,
    inmetroRegistry: 'INMETRO-123456',
    seoTitle: 'Óleo Motor 10W-40 Sintético 4 Litros',
    keywords: ['óleo motor', 'sintético', '10w40', 'lubrificante', 'mobil'],
    imageUrls: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop',
    ],
    oilSpecs: OilSpecs(
      saeGrade: '10W-40',
      chemicalBase: OilChemicalBase.synthetic,
      apiClassification: 'SN',
      aceaSpecs: 'A3/B4',
      jasoGrade: 'MA2',
      anpRegistry: '5557',
    ),
  ),

  // Bateria Automotiva
  Product(
    id: uuid.v4(),
    name: 'Bateria Automotiva 60Ah 12V',
    description: 'Bateria automotiva 60Ah 12V com tecnologia de cálcio',
    sku: 'BAT-60AH-12V-CAL',
    gtin: '7898765432103',
    partNumber: 'BAT-60AH-BR',
    oemCode: '',
    brand: 'Moura',
    price: 299.90,
    qualityRanking: QualityRanking.genuine,
    ncm: '85073099',
    cest: '1704900',
    cst: '070',
    monophasic: false,
    origin: MerchandiseOrigin.national,
    cfop: '5102',
    currentStock: 12,
    minimumStock: 3,
    maximumStock: 20,
    leadTimeDays: 5,
    physicalLocation: 'Corredor C, Prateleira 1',
    weight: 15.5,
    length: 23.0,
    width: 12.3,
    height: 22.5,
    inmetroRegistry: 'INMETRO-654321',
    seoTitle: 'Bateria 60Ah 12V Automóvel Moura',
    keywords: [
      'bateria',
      '60ah',
      'automotiva',
      '12v',
      'moura',
      'bateria carro'
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop&crop=entropy&cs=tinysrgb',
    ],
    batterySpecs: BatterySpecs(
      amperageAh: 60,
      cca: 500,
      polarity: 'Positivo à Direita',
      technology: BatteryTechnology.sli,
    ),
    compatibilities: [
      VehicleCompatibility(
        manufacturer: 'Fiat',
        model: 'Uno',
        version: '1.0 Fire',
        yearStart: 2010,
        yearEnd: 2023,
        motorization: '1.0',
        fuelType: FuelType.flex,
        position: 'Motor',
      ),
      VehicleCompatibility(
        manufacturer: 'Chevrolet',
        model: 'Celta',
        version: '1.0 LS',
        yearStart: 2008,
        yearEnd: 2016,
        motorization: '1.0',
        fuelType: FuelType.flex,
        position: 'Motor',
      ),
    ],
  ),

  // Pneu Automóvel
  Product(
    id: uuid.v4(),
    name: 'Pneu Aro 14 175/65R14',
    description: 'Pneu para automóvel aro 14 medida 175/65R14',
    sku: 'PNE-175-65R14',
    gtin: '7898765432104',
    partNumber: 'PNE-175-65R14-NAK',
    oemCode: '',
    brand: 'Nakata',
    price: 189.90,
    qualityRanking: QualityRanking.aftermarket,
    ncm: '40121099',
    cest: '2003600',
    cst: '070',
    monophasic: false,
    origin: MerchandiseOrigin.internalMarket,
    cfop: '5102',
    currentStock: 16,
    minimumStock: 4,
    maximumStock: 30,
    leadTimeDays: 10,
    physicalLocation: 'Corredor D, Prateleira 4',
    weight: 7.2,
    length: 53.0,
    width: 53.0,
    height: 20.0,
    inmetroRegistry: 'INMETRO-987654',
    seoTitle: 'Pneu Aro 14 175/65R14 Nakata',
    keywords: ['pneu', 'aro 14', '175/65r14', 'nakata', 'pneu carro'],
    imageUrls: [
      'https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=600&h=400&fit=crop',
    ],
    tireSpecs: TireSpecs(
      nominalMeasure: '175/65R14',
      loadIndex: 82,
      speedIndex: 'H',
      dotCode: 'NAK1424',
      fireNumber: '02',
    ),
  ),

  // Correia/Corrente
  Product(
    id: uuid.v4(),
    name: 'Correia Distribuição Fiat Uno 1.0',
    description: 'Correia de distribuição para motor 1.0 Fire',
    sku: 'COR-FIAT-UNO-1.0',
    gtin: '7898765432105',
    partNumber: 'COR-FIAT-FIRE',
    oemCode: '00038001',
    brand: 'Gates',
    price: 125.50,
    qualityRanking: QualityRanking.original,
    ncm: '40161399',
    cest: '2203000',
    cst: '070',
    monophasic: false,
    origin: MerchandiseOrigin.directImport,
    cfop: '5102',
    currentStock: 8,
    minimumStock: 3,
    maximumStock: 15,
    leadTimeDays: 12,
    physicalLocation: 'Corredor E, Prateleira 2',
    weight: 0.350,
    length: 12.0,
    width: 8.0,
    height: 3.0,
    seoTitle: 'Correia Distribuição Fiat Uno 1.0 Fire',
    keywords: ['correia distribuição', 'fiat uno', '1.0 fire', 'correia'],
    imageUrls: [
      'https://images.unsplash.com/photo-1487754180143-c282803316b3?w=600&h=400&fit=crop',
    ],
    compatibilities: [
      VehicleCompatibility(
        manufacturer: 'Fiat',
        model: 'Uno',
        version: '1.0 Fire',
        yearStart: 2001,
        yearEnd: 2010,
        motorization: '1.0',
        fuelType: FuelType.flex,
        position: 'Motor',
      ),
    ],
  ),

  // Filtro de Ar
  Product(
    id: uuid.v4(),
    name: 'Filtro de Ar Motor',
    description: 'Filtro de ar para motor de automóvel',
    sku: 'FIL-AR-MOTOR',
    gtin: '7898765432106',
    partNumber: 'FIL-AR-001',
    oemCode: '',
    brand: 'Bosch',
    price: 35.90,
    qualityRanking: QualityRanking.original,
    ncm: '84212399',
    cest: '2201500',
    cst: '070',
    monophasic: false,
    origin: MerchandiseOrigin.national,
    cfop: '5102',
    currentStock: 52,
    minimumStock: 10,
    maximumStock: 80,
    leadTimeDays: 5,
    physicalLocation: 'Corredor A, Prateleira 1',
    weight: 0.180,
    length: 10.5,
    width: 8.0,
    height: 6.5,
    seoTitle: 'Filtro de Ar Motor Bosch',
    keywords: ['filtro ar', 'motor', 'bosch', 'filtro automóvel'],
    imageUrls: [
      'https://images.unsplash.com/photo-1483389127117-b6a2102724ae?w=600&h=400&fit=crop',
    ],
  ),

  // Kit Corrente com Tensor
  Product(
    id: uuid.v4(),
    name: 'Kit Corrente para Moto 520',
    description:
        'Kit completo corrente 520 com pinhão e coroa para motocicleta',
    sku: 'KIT-CORR-520-MOTO',
    gtin: '7898765432107',
    partNumber: 'KIT-520-MOTO',
    oemCode: '',
    brand: 'Transmoto',
    price: 189.50,
    qualityRanking: QualityRanking.aftermarket,
    ncm: '87082099',
    cest: '2201500',
    cst: '070',
    monophasic: false,
    origin: MerchandiseOrigin.national,
    cfop: '5102',
    currentStock: 22,
    minimumStock: 5,
    maximumStock: 40,
    leadTimeDays: 8,
    physicalLocation: 'Corredor F, Prateleira 3',
    weight: 2.1,
    length: 15.0,
    width: 12.0,
    height: 8.0,
    seoTitle: 'Kit Corrente 520 Motocicleta com Pinhão e Coroa',
    keywords: ['corrente moto', 'kit transmissão', '520', 'pinhão coroa'],
    imageUrls: [
      'https://images.unsplash.com/photo-1507372341519-283ed47adf5d?w=600&h=400&fit=crop',
    ],
    transmissionKitSpecs: TransmissionKitSpecs(
      chainStep: 520,
      pinion: 15,
      crown: 42,
      oringType: 'Com O-ring',
    ),
  ),
];
